name: Deploy # Workflow 이름
on: # Event 감지
  push:
    branches:
      - main # 마스터 브랜치의 푸쉬가 일어날 때 CI/CD를 진행하겠다는 뜻
  pull_request:
    branches:
      - main
jobs: # Job 설정
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2

      - name: Check Node v # Node v 확인
        run: node -v

      - name: Start # Node Start
        run: npm run start

      - name: zip create # zip 파일을 만듭니다(파일명은 자유, 대신 아래 workflow에 적을 파일명과 동일하게 맞춰주세요).
        run: zip -qq -r ./build-be.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3 # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

        # 여기에서 S3버킷이름, 폴더이름을 바꿔주세요! 혹시 aws리전이 다르면 리전도 바꿔주세요.** 
        run: |
          aws s3 cp --region ap-northeast-2 ./build-be.zip s3://pd-bucket/deploy/build-be.zip
      
      - name: Deploy # Deploy to EC2
        run: aws deploy create-deployment
          --application-name pocket-doctor-app
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name deploy-group-name
          --s3-location bucket=pd-bucket,key=deploy/build-be.zip,bundleType=zip
